//! Best-effort JS dependency install for freshly materialized worktrees.
//!
//! Weft creates repo-native git worktrees but does not share one `node_modules`
//! across them (isolation, checkpoint, and concurrent agents all need a private
//! tree). For Node repos, the expensive part is usually re-downloading packages
//! per worktree. pnpm already optimizes that with a content-addressable store +
//! hard links, and its experimental Global Virtual Store is aimed at multi-
//! worktree / multi-agent checkouts.
//!
//! This module runs a package-manager install inside the worktree after
//! materialize succeeds:
//! - never fails materialize (worker can still install itself)
//! - skips non-Node trees and worktrees that already look installed
//! - honors lockfiles + `packageManager` before choosing a tool
//! - never runs lifecycle scripts on the automatic path
//! - never writes a new lockfile into the worker checkout
//! - for pnpm, prefers offline store reuse and may enable the global virtual
//!   store via env (no write into the user's repo config)

use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::time::{Duration, Instant};

/// Env-backed knobs for deps bootstrap. Tests pass an explicit `Config` so they
/// never race on process-global environment variables.
#[derive(Clone, Debug)]
pub(crate) struct Config {
    pub enabled: bool,
    /// None = wait unbounded.
    pub timeout: Option<Duration>,
    pub pnpm_global_virtual_store: bool,
}

impl Config {
    /// Production defaults from env:
    /// - `WEFT_DEPS_BOOTSTRAP=0|false|off|no` disables
    /// - `WEFT_DEPS_BOOTSTRAP_TIMEOUT_SECS` (default 600; 0 = unbounded)
    /// - `WEFT_PNPM_GLOBAL_VIRTUAL_STORE=0|false|off|no` disables experimental GVS
    pub fn from_env() -> Self {
        Self {
            enabled: env_flag_enabled("WEFT_DEPS_BOOTSTRAP", true),
            timeout: {
                let secs = std::env::var("WEFT_DEPS_BOOTSTRAP_TIMEOUT_SECS")
                    .ok()
                    .and_then(|v| v.trim().parse::<u64>().ok())
                    .unwrap_or(600);
                if secs == 0 {
                    None
                } else {
                    Some(Duration::from_secs(secs))
                }
            },
            pnpm_global_virtual_store: env_flag_enabled("WEFT_PNPM_GLOBAL_VIRTUAL_STORE", true),
        }
    }
}

fn env_flag_enabled(key: &str, default: bool) -> bool {
    match std::env::var(key) {
        Ok(v) => {
            let t = v.trim().to_ascii_lowercase();
            !matches!(t.as_str(), "0" | "false" | "off" | "no")
        }
        Err(_) => default,
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum PackageManager {
    Pnpm,
    YarnClassic,
    YarnBerry,
    Npm,
    Bun,
}

impl PackageManager {
    fn as_str(&self) -> &'static str {
        match self {
            PackageManager::Pnpm => "pnpm",
            PackageManager::YarnClassic | PackageManager::YarnBerry => "yarn",
            PackageManager::Npm => "npm",
            PackageManager::Bun => "bun",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct InstallPlan {
    pub cwd: PathBuf,
    pub program: String,
    pub args: Vec<String>,
    /// Extra env pairs applied only for this install (e.g. pnpm virtual store).
    pub env: Vec<(String, String)>,
}

/// Parse packageManager field like "pnpm@9.0.0" / "yarn@4.1.0" / "bun@1.2.0".
fn declared_package_manager(dir: &Path) -> Option<String> {
    let raw = std::fs::read_to_string(dir.join("package.json")).ok()?;
    let json: serde_json::Value = serde_json::from_str(&raw).ok()?;
    let pm = json.get("packageManager")?.as_str()?.trim();
    if pm.is_empty() {
        None
    } else {
        Some(pm.to_ascii_lowercase())
    }
}

fn declared_tool_name(declared: &str) -> &str {
    declared.split('@').next().unwrap_or(declared)
}

fn yarn_lock_is_berry(dir: &Path) -> bool {
    // Yarn Berry lockfiles start with `__metadata:`; Classic starts with
    // `# THIS IS AN AUTOGENERATED FILE` / `# yarn lockfile v1`.
    match std::fs::read_to_string(dir.join("yarn.lock")) {
        Ok(s) => s.lines().take(20).any(|l| l.starts_with("__metadata")),
        Err(_) => false,
    }
}

/// Detect the package manager from lockfiles + packageManager. None when there
/// is no package.json, or when the declared tool is unsupported / ambiguous in
/// a way that would risk writing the wrong lockfile.
pub(crate) fn detect_package_manager(dir: &Path) -> Option<PackageManager> {
    if !dir.join("package.json").is_file() {
        return None;
    }

    let declared = declared_package_manager(dir);
    let declared_tool = declared.as_deref().map(declared_tool_name);

    // Lockfiles are the strongest signal when present.
    if dir.join("pnpm-lock.yaml").is_file() {
        return Some(PackageManager::Pnpm);
    }
    if dir.join("yarn.lock").is_file() {
        if yarn_lock_is_berry(dir)
            || declared_tool == Some("yarn")
                && declared
                    .as_deref()
                    .and_then(|d| d.split('@').nth(1))
                    .and_then(|v| v.split('.').next())
                    .and_then(|maj| maj.parse::<u32>().ok())
                    .is_some_and(|maj| maj >= 2)
        {
            return Some(PackageManager::YarnBerry);
        }
        return Some(PackageManager::YarnClassic);
    }
    if dir.join("bun.lock").is_file() || dir.join("bun.lockb").is_file() {
        return Some(PackageManager::Bun);
    }
    if dir.join("package-lock.json").is_file() || dir.join("npm-shrinkwrap.json").is_file() {
        return Some(PackageManager::Npm);
    }

    // No lockfile: honor packageManager, never invent npm for a declared non-npm tool.
    match declared_tool {
        Some("pnpm") => Some(PackageManager::Pnpm),
        Some("yarn") => {
            let major = declared
                .as_deref()
                .and_then(|d| d.split('@').nth(1))
                .and_then(|v| v.split('.').next())
                .and_then(|maj| maj.parse::<u32>().ok())
                .unwrap_or(1);
            if major >= 2 {
                Some(PackageManager::YarnBerry)
            } else {
                Some(PackageManager::YarnClassic)
            }
        }
        Some("bun") => Some(PackageManager::Bun),
        Some("npm") => Some(PackageManager::Npm),
        Some(_) => None, // unknown declared tool — do not guess
        None => Some(PackageManager::Npm),
    }
}


/// True when every non-optional declared dependency exists under node_modules.
/// Used as a Bun completion fallback so a partial install cannot look ready.
fn all_top_level_deps_present(dir: &Path, node_modules: &Path) -> bool {
    let Ok(raw) = std::fs::read_to_string(dir.join("package.json")) else {
        return false;
    };
    let Ok(json) = serde_json::from_str::<serde_json::Value>(&raw) else {
        return false;
    };
    let mut any = false;
    for key in ["dependencies", "devDependencies"] {
        let Some(obj) = json.get(key).and_then(|v| v.as_object()) else {
            continue;
        };
        for name in obj.keys() {
            any = true;
            // Scoped packages live at node_modules/@scope/name
            if !node_modules.join(name).is_dir() {
                return false;
            }
        }
    }
    any
}

/// True when the worktree already has a usable dependency install.
pub(crate) fn node_modules_ready(dir: &Path) -> bool {
    let Some(pm) = detect_package_manager(dir) else {
        return false;
    };
    match pm {
        PackageManager::Pnpm => {
            let nm = dir.join("node_modules");
            nm.is_dir() && nm.join(".modules.yaml").is_file()
        }
        PackageManager::YarnBerry => {
            // PnP: .pnp.cjs / .pnp.js; node-modules linker: non-empty node_modules.
            // install-state is also evidence of a completed Berry install.
            dir.join(".pnp.cjs").is_file()
                || dir.join(".pnp.js").is_file()
                || dir.join(".yarn/install-state.gz").is_file()
                || {
                    let nm = dir.join("node_modules");
                    nm.is_dir()
                        && std::fs::read_dir(&nm)
                            .map(|mut e| e.next().is_some())
                            .unwrap_or(false)
                }
        }
        PackageManager::YarnClassic => {
            // Classic writes `.yarn-integrity` only after a successful install.
            let nm = dir.join("node_modules");
            nm.is_dir() && nm.join(".yarn-integrity").is_file()
        }
        PackageManager::Npm => {
            // Modern npm writes `node_modules/.package-lock.json` on success.
            // Without it, a partial tree (timeout mid-install) must not count as ready.
            let nm = dir.join("node_modules");
            nm.is_dir() && nm.join(".package-lock.json").is_file()
        }
        PackageManager::Bun => {
            // Prefer Bun's own metadata; otherwise require EVERY declared
            // top-level dependency so a partial install cannot look ready.
            let nm = dir.join("node_modules");
            nm.is_dir()
                && (nm.join(".bun").exists() || all_top_level_deps_present(dir, &nm))
        }
    }
}


/// True when the worktree's Yarn config can load repository-controlled code
/// (`yarnPath` / `yarn-path` / Berry plugins). Automatic bootstrap must not
/// invoke Yarn in that case — the worker can still install itself later.

/// True when `child` is the same as or under `parent` after canonicalize.
fn path_is_under(parent: &Path, child: &Path) -> bool {
    let Ok(p) = parent.canonicalize() else {
        return false;
    };
    let Ok(c) = child.canonicalize() else {
        // For non-existent paths, compare components after absolute join.
        let c = if child.is_absolute() {
            child.to_path_buf()
        } else {
            parent.join(child)
        };
        return c.starts_with(&p);
    };
    c.starts_with(p)
}

/// True when a relative path component could escape the worktree (../).
#[allow(dead_code)]
fn relative_path_escapes(s: &str) -> bool {
    let p = Path::new(s);
    for c in p.components() {
        if matches!(c, std::path::Component::ParentDir) {
            return true;
        }
    }
    false
}

/// True when package-manager output trees are gitignored in this worktree.
/// Bootstrap creates large untracked trees; if they are not ignored they leak
/// into worker diffs via `git ls-files --others --exclude-standard`.
fn output_tree_is_gitignored(dir: &Path, rel: &str) -> bool {
    // Prefer git check-ignore when available.
    let out = std::process::Command::new("git")
        .args(["check-ignore", "-q", "--", rel])
        .current_dir(dir)
        .status();
    match out {
        Ok(st) if st.success() => true,
        _ => {
            // Fallback: look for a plain ignore rule in .gitignore / .git/info/exclude.
            for name in [".gitignore", ".git/info/exclude"] {
                if let Ok(raw) = std::fs::read_to_string(dir.join(name)) {
                    for line in raw.lines() {
                        let l = line.trim();
                        if l.is_empty() || l.starts_with('#') {
                            continue;
                        }
                        if l == rel
                            || l == format!("/{rel}")
                            || l == format!("{rel}/")
                            || l == format!("/{rel}/")
                            || l == format!("**/{rel}")
                            || l == format!("**/{rel}/")
                        {
                            return true;
                        }
                    }
                }
            }
            false
        }
    }
}

/// Scan worktree + ancestor dirs (up to repo root / filesystem root, bounded)
/// for Yarn configs that can execute code or redirect install artifacts.
fn yarn_risky_config_in_scope(dir: &Path) -> bool {
    // Local first.
    if yarn_config_executes_repo_code(dir) {
        return true;
    }
    // Ancestors: Yarn walks up for .yarnrc.yml.
    let mut cur = dir.to_path_buf();
    for _ in 0..8 {
        let Some(parent) = cur.parent() else {
            break;
        };
        if parent == cur {
            break;
        }
        // Stop after leaving a git worktree root if we can detect it.
        if cur.join(".git").exists() {
            // already scanned local; ancestors beyond the git root still matter
            // for yarn, but keep bounded.
        }
        if yarn_config_executes_repo_code(parent) {
            return true;
        }
        cur = parent.to_path_buf();
    }
    false
}

/// Ensure critical output roots are real directories inside the worktree (not
/// symlinks that escape to the canonical repo).
fn ensure_contained_output_dirs(dir: &Path, rels: &[&str]) -> bool {
    for rel in rels {
        let path = dir.join(rel);
        if path.exists() || path.symlink_metadata().is_ok() {
            // If it's a symlink, require the target to stay under the worktree.
            if let Ok(meta) = std::fs::symlink_metadata(&path) {
                if meta.file_type().is_symlink() {
                    if !path_is_under(dir, &path) {
                        return false;
                    }
                }
            }
            if path.exists() && !path_is_under(dir, &path) {
                return false;
            }
        } else {
            // Create a real directory so package managers cannot follow a
            // later-created escape symlink planted mid-install.
            if std::fs::create_dir_all(&path).is_err() {
                return false;
            }
            if !path_is_under(dir, &path) {
                return false;
            }
        }
    }
    true
}

fn yarn_config_executes_repo_code(dir: &Path) -> bool {
    // yarn.config.cjs is loaded for constraints checks / hooks.
    if dir.join("yarn.config.cjs").is_file() || dir.join("yarn.config.js").is_file() {
        return true;
    }
    for name in [".yarnrc.yml", ".yarnrc.yaml", ".yarnrc"] {
        let Ok(raw) = std::fs::read_to_string(dir.join(name)) else {
            continue;
        };
        let lower = raw.to_ascii_lowercase();
        if lower.contains("yarnpath")
            || lower.contains("yarn-path")
            || lower.contains("plugins:")
            || lower.contains("pluginpath")
            || lower.contains("enableconstraintschecks")
            || lower.contains("constraints")
            || lower.contains("installstatepath")
            || lower.contains("pnpunpluggedfolder")
            || lower.contains("pnppath")
            || lower.contains("pnpcachedatapath")
            || lower.contains("globalfolder")
            || lower.contains("cachedir")
            || lower.contains("cachefolder")
            || lower.contains("virtualfolder")
        {
            return true;
        }
    }
    // Checked-in Yarn binary / plugin payloads under .yarn/ are also a signal
    // that the project expects to load local Yarn code.
    if dir.join(".yarn/releases").is_dir() || dir.join(".yarn/plugins").is_dir() {
        return true;
    }
    false
}


/// True when a project package-manager config can interpolate process env into
/// registry auth (e.g. `_authToken=${GITHUB_TOKEN}`). Automatic bootstrap
/// refuses these trees rather than risk secret exfiltration.
fn project_config_interpolates_env_secrets(dir: &Path) -> bool {
    for name in [".npmrc", ".yarnrc", ".yarnrc.yml", ".yarnrc.yaml"] {
        let Ok(raw) = std::fs::read_to_string(dir.join(name)) else {
            continue;
        };
        let lower = raw.to_ascii_lowercase();
        if lower.contains("${")
            && (lower.contains("authtoken")
                || lower.contains("_auth")
                || lower.contains("password")
                || lower.contains("token"))
        {
            return true;
        }
    }
    false
}

/// Build the install plan from process env, or None when bootstrap should be skipped.
#[allow(dead_code)]
pub(crate) fn plan_install(dir: &Path) -> Option<InstallPlan> {
    plan_install_with(dir, &Config::from_env())
}

/// Build the install plan with an explicit config (used by tests to avoid env races).
pub(crate) fn plan_install_with(dir: &Path, cfg: &Config) -> Option<InstallPlan> {
    if !cfg.enabled {
        return None;
    }
    if !dir.is_dir() {
        return None;
    }
    let pm = detect_package_manager(dir)?;
    if node_modules_ready(dir) {
        return None;
    }
    if project_config_interpolates_env_secrets(dir) {
        return None;
    }
    // Bootstrap output must not become worker-visible git changes.
    if !output_tree_is_gitignored(dir, "node_modules") {
        return None;
    }
    // Prevent symlink escape of install outputs into the canonical repo.
    if !ensure_contained_output_dirs(
        dir,
        &[
            "node_modules",
            "node_modules/.pnpm",
            "node_modules/.weft-pnpm-store",
            "node_modules/.weft-npm-cache",
        ],
    ) {
        return None;
    }

    let mut env = Vec::new();
    // Automatic bootstrap must NOT run lifecycle scripts (untrusted repos / agent
    // branches). Workers that need scripts can install themselves later.
    let (program, args) = match pm {
        PackageManager::Pnpm => {
            // Containment: force modules + virtual store inside the worktree so a
            // malicious .npmrc `modules-dir=../../../...` cannot write into the
            // canonical repo. Also ignore pnpmfile hooks (they run JS even with
            // --ignore-scripts).
            let mut args = vec![
                "install".to_string(),
                "--prefer-offline".to_string(),
                "--ignore-scripts".to_string(),
                "--ignore-pnpmfile".to_string(),
                "--modules-dir".to_string(),
                "node_modules".to_string(),
                "--virtual-store-dir".to_string(),
                "node_modules/.pnpm".to_string(),
                // Keep the content-addressable store inside the worktree so a
                // project .npmrc store-dir cannot write into the canonical repo.
                // Shared global store is sacrificed for isolation on this path.
                "--store-dir".to_string(),
                "node_modules/.weft-pnpm-store".to_string(),
            ];
            // Only ignore a *parent* workspace. If this worktree itself is a
            // pnpm workspace, we must install all packages.
            if !(dir.join("pnpm-workspace.yaml").is_file()
                || dir.join("pnpm-workspace.yml").is_file())
            {
                args.push("--ignore-workspace".to_string());
            }
            // Immutable only: never rewrite the tracked lockfile from bootstrap.
            if dir.join("pnpm-lock.yaml").is_file() {
                args.push("--frozen-lockfile".to_string());
            } else {
                // No lockfile: still avoid creating one in the worker checkout.
                args.push("--lockfile".to_string());
                args.push("false".to_string());
            }
            if cfg.pnpm_global_virtual_store {
                env.push((
                    "npm_config_enable_global_virtual_store".to_string(),
                    "true".to_string(),
                ));
            }
            ("pnpm".to_string(), args)
        }
        PackageManager::YarnClassic => {
            // Skip when the project can load repo-controlled Yarn code or
            // redirect install artifacts outside the worktree.
            if yarn_risky_config_in_scope(dir) {
                return None;
            }
            let mut args = vec![
                "install".to_string(),
                "--prefer-offline".to_string(),
                "--ignore-scripts".to_string(),
            ];
            if dir.join("yarn.lock").is_file() {
                // Immutable when a lockfile exists.
                args.push("--frozen-lockfile".to_string());
            } else {
                // Lockless: never create yarn.lock in the worker checkout.
                args.push("--no-lockfile".to_string());
            }
            ("yarn".to_string(), args)
        }
        // Berry rejects Classic-only flags like --prefer-offline.
        PackageManager::YarnBerry => {
            // yarnPath / plugins in .yarnrc.yml execute repo JS before install.
            // Do not auto-bootstrap those trees.
            if yarn_risky_config_in_scope(dir) {
                return None;
            }
            // Without a lockfile, Berry would create/update yarn.lock — skip.
            if !dir.join("yarn.lock").is_file() {
                return None;
            }
            // Ignore project yarnPath via env (defense in depth if config scan misses).
            env.push(("YARN_IGNORE_PATH".to_string(), "1".to_string()));
            env.push(("YARN_ENABLE_IMMUTABLE_INSTALLS".to_string(), "true".to_string()));
            (
                "yarn".to_string(),
                vec![
                    "install".to_string(),
                    "--immutable".to_string(),
                    "--mode=skip-build".to_string(), // skip build scripts (Berry)
                ],
            )
        }
        PackageManager::Npm => {
            // Force local install into this worktree. Project .npmrc can set
            // global=true / prefix=../../../... and otherwise write into the
            // canonical repo above .worktrees/.
            env.push(("npm_config_global".to_string(), "false".to_string()));
            env.push((
                "npm_config_prefix".to_string(),
                dir.to_string_lossy().into_owned(),
            ));
            // Pin cache inside the worktree so relative cache=../../../... in
            // project .npmrc cannot write into the canonical repository.
            env.push((
                "npm_config_cache".to_string(),
                dir.join("node_modules/.weft-npm-cache")
                    .to_string_lossy()
                    .into_owned(),
            ));
            if dir.join("package-lock.json").is_file() || dir.join("npm-shrinkwrap.json").is_file() {
                (
                    "npm".to_string(),
                    vec![
                        "ci".to_string(),
                        "--prefer-offline".to_string(),
                        "--ignore-scripts".to_string(),
                        "--no-global".to_string(),
                    ],
                )
            } else {
                // Do not create package-lock.json in the worker checkout.
                (
                    "npm".to_string(),
                    vec![
                        "install".to_string(),
                        "--prefer-offline".to_string(),
                        "--ignore-scripts".to_string(),
                        "--no-package-lock".to_string(),
                        "--no-global".to_string(),
                    ],
                )
            }
        }
        PackageManager::Bun => {
            let mut args = vec!["install".to_string(), "--ignore-scripts".to_string()];
            if dir.join("bun.lock").is_file() || dir.join("bun.lockb").is_file() {
                // Immutable when a lockfile exists.
                args.push("--frozen-lockfile".to_string());
            } else {
                // Without a lockfile, prevent bun.lock creation in the worker tree.
                args.push("--no-save".to_string());
            }
            ("bun".to_string(), args)
        }
    };

    Some(InstallPlan {
        cwd: dir.to_path_buf(),
        program,
        args,
        env,
    })
}

/// Truncate to the last ~`max` bytes, only on a UTF-8 character boundary.
fn output_tail(bytes: &[u8], max: usize) -> String {
    if bytes.len() <= max {
        return String::from_utf8_lossy(bytes).trim().to_string();
    }
    let mut start = bytes.len() - max;
    // Walk forward to a char boundary so lossy conversion never panics if we
    // later slice the String (and so we don't drop half a character silently
    // in a confusing way).
    while start < bytes.len() && (bytes[start] & 0b1100_0000) == 0b1000_0000 {
        start += 1;
    }
    let s = String::from_utf8_lossy(&bytes[start..]);
    let slice = s.find('\n').map(|i| &s[i + 1..]).unwrap_or(&s);
    format!("…{}", slice.trim())
}

fn looks_like_frozen_lockfile_error(stderr: &[u8], stdout: &[u8]) -> bool {
    let combined = {
        let mut v = Vec::with_capacity(stderr.len() + stdout.len());
        v.extend_from_slice(stderr);
        v.extend_from_slice(stdout);
        String::from_utf8_lossy(&v).to_ascii_lowercase()
    };
    combined.contains("frozen-lockfile")
        || combined.contains("lockfile is out of date")
        || combined.contains("lockfile was modified")
        || combined.contains("pnpm-lock.yaml is not up to date")
        || combined.contains("err_pnpm_out_of_date")
        || combined.contains("err_pnpm_lockfile")
}

/// Run one install plan. Immutable only — never rewrite lockfiles on failure.
fn run_plan(plan: &InstallPlan, overall_timeout: Option<Duration>) -> Result<(), String> {
    let out = run_command(plan, overall_timeout)?;
    if out.status.success() {
        return Ok(());
    }
    Err(format!(
        "{} {} failed: exit {} — {}",
        plan.program,
        plan.args.join(" "),
        out.status.code().unwrap_or(-1),
        output_tail(&out.stderr, 400)
    ))
}


/// Drop relative PATH entries (especially ".") so child resolution cannot pick
/// up a package-manager binary planted in the untrusted worktree.
/// Platform-aware: uses OS path separators and preserves drive-letter paths.
fn sanitize_path_for_bootstrap(path: &str) -> String {
    let entries: Vec<std::path::PathBuf> = std::env::split_paths(path)
        .filter(|e| !e.as_os_str().is_empty())
        .filter(|e| e.is_absolute())
        .collect();
    std::env::join_paths(entries)
        .map(|os| os.to_string_lossy().into_owned())
        .unwrap_or_default()
}

/// Resolve `program` against the sanitized tool PATH to an absolute path.
fn resolve_package_manager_program(program: &str) -> Result<PathBuf, String> {
    let path = sanitize_path_for_bootstrap(&crate::detect::tool_path());
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(program);
        if candidate.is_file() {
            return Ok(candidate);
        }
        #[cfg(windows)]
        {
            for ext in ["exe", "cmd", "bat"] {
                let c = dir.join(format!("{program}.{ext}"));
                if c.is_file() {
                    return Ok(c);
                }
            }
        }
    }
    Ok(PathBuf::from(program))
}

fn bootstrap_identity_envs() -> Vec<(String, String)> {
    let mut out = Vec::new();
    for key in ["HOME", "USER", "LOGNAME", "LANG", "LC_ALL", "TMPDIR"] {
        if let Ok(v) = std::env::var(key) {
            if !v.is_empty() {
                out.push((key.to_string(), v));
            }
        }
    }
    if !out.iter().any(|(k, _)| k == "TMPDIR") {
        out.push((
            "TMPDIR".to_string(),
            std::env::temp_dir().to_string_lossy().into_owned(),
        ));
    }
    out
}

fn bootstrap_cache_home_envs() -> Vec<(String, String)> {
    let mut out = Vec::new();
    for key in [
        "XDG_CACHE_HOME",
        "XDG_CONFIG_HOME",
        "APPDATA",
        "LOCALAPPDATA",
        "USERPROFILE",
    ] {
        if let Ok(v) = std::env::var(key) {
            if !v.is_empty() {
                out.push((key.to_string(), v));
            }
        }
    }
    out
}

fn run_command(plan: &InstallPlan, timeout: Option<Duration>) -> Result<Output, String> {
    // Resolve to an absolute executable BEFORE entering the worktree so a
    // relative PATH entry (e.g. ".") cannot pick up a repo-provided binary.
    let program = resolve_package_manager_program(&plan.program)?;
    let path = sanitize_path_for_bootstrap(&crate::detect::tool_path());
    let mut cmd = Command::new(&program);
    cmd.args(&plan.args)
        .current_dir(&plan.cwd)
        // Do NOT inherit Weft's full environment: project package-manager
        // configs can interpolate secrets into registry auth.
        .env_clear()
        .env("PATH", path)
        .envs(bootstrap_identity_envs())
        .envs(bootstrap_cache_home_envs())
        .env("TERM", "dumb")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    for (k, v) in &plan.env {
        cmd.env(k, v);
    }

    // Own process group so a timeout can kill the whole install tree (pm +
    // any remaining child helpers). Lifecycle scripts are already disabled,
    // but package managers still spawn helpers.
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        // Safety: setpgid in the child before exec; no other threads share this
        // child's address space yet.
        unsafe {
            cmd.pre_exec(|| {
                if libc::setpgid(0, 0) != 0 {
                    return Err(std::io::Error::last_os_error());
                }
                Ok(())
            });
        }
    }

    let child = cmd
        .spawn()
        .map_err(|e| format!("could not spawn {}: {e}", plan.program))?;

    let finished = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    let killer = timeout.map(|limit| {
        let finished = finished.clone();
        let pid = child.id();
        std::thread::spawn(move || {
            let start = Instant::now();
            while start.elapsed() < limit {
                if finished.load(std::sync::atomic::Ordering::SeqCst) {
                    return;
                }
                std::thread::sleep(Duration::from_millis(50));
            }
            if finished.load(std::sync::atomic::Ordering::SeqCst) {
                return;
            }
            kill_process_tree(pid);
        })
    });

    let out = child
        .wait_with_output()
        .map_err(|e| format!("could not run {}: {e}", plan.program));
    finished.store(true, std::sync::atomic::Ordering::SeqCst);
    if let Some(h) = killer {
        let _ = h.join();
    }
    let out = out?;
    if let Some(limit) = timeout {
        if !out.status.success()
            && out.stdout.is_empty()
            && out.stderr.is_empty()
            && out.status.code().unwrap_or(0) != 1
        {
            return Err(format!(
                "{} timed out or was killed after {}s",
                plan.program,
                limit.as_secs()
            ));
        }
    }
    Ok(out)
}

#[cfg(unix)]
fn kill_process_tree(pid: u32) {
    // Negative PID = process group. We put the child in its own group at spawn.
    unsafe {
        let _ = libc::kill(-(pid as i32), libc::SIGKILL);
        // Fallback if setpgid failed for any reason.
        let _ = libc::kill(pid as i32, libc::SIGKILL);
    }
}

#[cfg(not(unix))]
fn kill_process_tree(pid: u32) {
    let _ = Command::new("taskkill")
        .args(["/PID", &pid.to_string(), "/T", "/F"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

/// Best-effort install for one worktree path. Never panics; logs and returns.
pub fn maybe_bootstrap(worktree: &Path) {
    let cfg = Config::from_env();
    let Some(plan) = plan_install_with(worktree, &cfg) else {
        return;
    };
    let label = format!(
        "{} {} in {}",
        plan.program,
        plan.args.join(" "),
        worktree.display()
    );
    let started = Instant::now();
    match run_plan(&plan, cfg.timeout) {
        Ok(()) => {
            eprintln!(
                "[weft] deps bootstrap ok ({:.1}s): {label}",
                started.elapsed().as_secs_f64()
            );
        }
        Err(err) => {
            eprintln!(
                "[weft] deps bootstrap skipped after {:.1}s: {label}: {err}",
                started.elapsed().as_secs_f64()
            );
        }
    }
}

/// Bootstrap every worktree path in a materialize result (best-effort).
#[allow(dead_code)]
pub fn maybe_bootstrap_worktrees<'a, I>(paths: I)
where
    I: IntoIterator<Item = &'a str>,
{
    for p in paths {
        maybe_bootstrap(Path::new(p));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn tmp() -> PathBuf {
        static N: AtomicU64 = AtomicU64::new(0);
        let id = N.fetch_add(1, Ordering::Relaxed);
        let d = std::env::temp_dir().join(format!(
            "weft-deps-{}-{}-{}",
            std::process::id(),
            id,
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    fn write(dir: &Path, rel: &str, body: &str) {
        let p = dir.join(rel);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(p, body).unwrap();
    }

    fn test_cfg(enabled: bool, gvs: bool) -> Config {
        Config {
            enabled,
            timeout: Some(Duration::from_secs(30)),
            pnpm_global_virtual_store: gvs,
        }
    }

    #[test]
    fn detect_pm_from_lockfiles() {
        let d = tmp();
        write(&d, "package.json", "{}");
        assert_eq!(detect_package_manager(&d), Some(PackageManager::Npm));

        write(&d, "yarn.lock", "# yarn lockfile v1\n");
        assert_eq!(detect_package_manager(&d), Some(PackageManager::YarnClassic));

        write(&d, "pnpm-lock.yaml", "");
        assert_eq!(detect_package_manager(&d), Some(PackageManager::Pnpm));
    }

    #[test]
    fn detect_pm_none_without_package_json() {
        let d = tmp();
        write(&d, "README.md", "hi");
        assert_eq!(detect_package_manager(&d), None);
    }

    #[test]
    fn detect_pm_honors_declared_bun_without_guessing_npm() {
        let d = tmp();
        write(
            &d,
            "package.json",
            r#"{ "packageManager": "bun@1.2.0" }"#,
        );
        assert_eq!(detect_package_manager(&d), Some(PackageManager::Bun));
    }

    #[test]
    fn detect_pm_bun_lockfile() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "bun.lock", "");
        assert_eq!(detect_package_manager(&d), Some(PackageManager::Bun));
    }

    #[test]
    fn detect_yarn_berry_from_lock_metadata() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "yarn.lock", "__metadata:\n  version: 6\n");
        assert_eq!(detect_package_manager(&d), Some(PackageManager::YarnBerry));
    }

    #[test]
    fn node_modules_ready_pnpm_requires_modules_yaml() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "pnpm-lock.yaml", "");
        assert!(!node_modules_ready(&d));
        std::fs::create_dir_all(d.join("node_modules")).unwrap();
        assert!(!node_modules_ready(&d));
        write(&d, "node_modules/.modules.yaml", "hoistPattern: []\n");
        assert!(node_modules_ready(&d));
    }

    #[test]
    fn node_modules_ready_yarn_berry_accepts_pnp() {
        let d = tmp();
        write(&d, "package.json", r#"{ "packageManager": "yarn@4.0.0" }"#);
        write(&d, "yarn.lock", "__metadata:\n  version: 8\n");
        assert!(!node_modules_ready(&d));
        write(&d, ".pnp.cjs", "// pnp\n");
        assert!(node_modules_ready(&d));
    }

    #[test]
    fn node_modules_ready_npm_needs_package_lock_marker() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "package-lock.json", "{}");
        assert!(!node_modules_ready(&d));
        std::fs::create_dir_all(d.join("node_modules")).unwrap();
        write(&d, "node_modules/left-pad/package.json", "{}");
        assert!(!node_modules_ready(&d), "partial tree without integrity is not ready");
        write(&d, "node_modules/.package-lock.json", "{}");
        assert!(node_modules_ready(&d));
    }

    #[test]
    fn plan_install_skips_when_ready() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "pnpm-lock.yaml", "");
        std::fs::create_dir_all(d.join("node_modules")).unwrap();
        write(&d, "node_modules/.modules.yaml", "x\n");
        assert!(plan_install_with(&d, &test_cfg(true, true)).is_none());
    }

    #[test]
    fn plan_install_pnpm_uses_frozen_ignore_scripts_and_prefer_offline() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{"name":"x"}"#);
        write(&d, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n");
        let plan = plan_install_with(&d, &test_cfg(true, true)).expect("plan");
        assert_eq!(plan.program, "pnpm");
        assert!(plan.args.iter().any(|a| a == "install"));
        assert!(plan.args.iter().any(|a| a == "--prefer-offline"));
        assert!(plan.args.iter().any(|a| a == "--frozen-lockfile"));
        assert!(plan.args.iter().any(|a| a == "--ignore-scripts"));
        assert!(plan.args.iter().any(|a| a == "--ignore-pnpmfile"));
        assert!(plan.args.iter().any(|a| a == "--ignore-workspace"));
        assert!(plan
            .args
            .windows(2)
            .any(|w| w[0] == "--modules-dir" && w[1] == "node_modules"));
        assert!(plan
            .args
            .windows(2)
            .any(|w| w[0] == "--store-dir" && w[1] == "node_modules/.weft-pnpm-store"));
        assert!(plan
            .env
            .iter()
            .any(|(k, v)| k == "npm_config_enable_global_virtual_store" && v == "true"));
    }

    #[test]
    fn plan_install_npm_ci_when_lock_present() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", "{}");
        write(&d, "package-lock.json", "{}");
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "npm");
        assert_eq!(plan.args[0], "ci");
        assert!(plan.args.iter().any(|a| a == "--ignore-scripts"));
    }

    #[test]
    fn plan_install_npm_without_lock_does_not_create_lockfile() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", "{}");
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "npm");
        assert!(plan.args.iter().any(|a| a == "--no-package-lock"));
        assert!(plan.args.iter().any(|a| a == "--ignore-scripts"));
    }

    #[test]
    fn plan_install_yarn_classic_lockless_uses_no_lockfile() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{ "packageManager": "yarn@1.22.0" }"#);
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "yarn");
        assert!(plan.args.iter().any(|a| a == "--no-lockfile"));
        assert!(!plan.args.iter().any(|a| a == "--frozen-lockfile"));
    }

    #[test]
    fn plan_install_yarn_berry_is_immutable_and_skips_classic_flags() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{ "packageManager": "yarn@4.1.0" }"#);
        write(&d, "yarn.lock", "__metadata:
  version: 8
");
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "yarn");
        assert!(!plan.args.iter().any(|a| a == "--prefer-offline"));
        assert!(plan.args.iter().any(|a| a == "--immutable"));
        assert!(plan.args.iter().any(|a| a == "--mode=skip-build"));
        assert!(plan
            .env
            .iter()
            .any(|(k, v)| k == "YARN_IGNORE_PATH" && v == "1"));
    }

    #[test]
    fn plan_install_yarn_berry_skips_when_yarnpath_configured() {
        let d = tmp();
        write(&d, "package.json", r#"{ "packageManager": "yarn@4.1.0" }"#);
        write(&d, "yarn.lock", "__metadata:
  version: 8
");
        write(&d, ".yarnrc.yml", "yarnPath: .yarn/releases/yarn-4.1.0.cjs
");
        assert!(plan_install_with(&d, &test_cfg(true, false)).is_none());
    }

    #[test]
    fn plan_install_yarn_skips_when_yarn_config_cjs_present() {
        let d = tmp();
        write(&d, "package.json", r#"{ "packageManager": "yarn@4.1.0" }"#);
        write(&d, "yarn.lock", "__metadata:
  version: 8
");
        write(&d, "yarn.config.cjs", "module.exports = {};
");
        assert!(plan_install_with(&d, &test_cfg(true, false)).is_none());
    }

    #[test]
    fn plan_install_bun_without_lock_uses_no_save() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{ "packageManager": "bun@1.2.0" }"#);
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "bun");
        assert!(plan.args.iter().any(|a| a == "--no-save"));
        assert!(plan.args.iter().any(|a| a == "--ignore-scripts"));
    }

    #[test]
    fn plan_install_bun_with_lock_is_frozen() {
        let d = tmp();
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{ "packageManager": "bun@1.2.0" }"#);
        write(&d, "bun.lock", "");
        let plan = plan_install_with(&d, &test_cfg(true, false)).expect("plan");
        assert_eq!(plan.program, "bun");
        assert!(plan.args.iter().any(|a| a == "--frozen-lockfile"));
        assert!(!plan.args.iter().any(|a| a == "--no-save"));
    }

    #[test]
    fn plan_install_skips_when_npmrc_interpolates_auth_token() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "package-lock.json", "{}");
        write(
            &d,
            ".npmrc",
            "//registry.example.com/:_authToken=${GITHUB_TOKEN}
",
        );
        assert!(plan_install_with(&d, &test_cfg(true, false)).is_none());
    }


    #[test]
    fn plan_install_skips_when_node_modules_not_ignored() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "package-lock.json", "{}");
        // no gitignore → skip
        assert!(plan_install_with(&d, &test_cfg(true, false)).is_none());
    }

    #[test]
    fn plan_install_pnpm_ignores_workspace_only_without_local_manifest() {
        let d = tmp();
        // minimal git repo so check-ignore works if used; also add ignore rule
        let _ = std::process::Command::new("git").args(["init"]).current_dir(&d).status();
        write(&d, ".gitignore", "node_modules/\n");
        write(&d, "package.json", r#"{"name":"x"}"#);
        write(&d, "pnpm-lock.yaml", "lockfileVersion: '9.0'\n");
        let plan = plan_install_with(&d, &test_cfg(true, true)).expect("plan");
        assert!(plan.args.iter().any(|a| a == "--ignore-workspace"));

        // local workspace manifest → do not ignore workspace
        write(&d, "pnpm-workspace.yaml", "packages: ['packages/*']\n");
        let plan2 = plan_install_with(&d, &test_cfg(true, true)).expect("plan2");
        assert!(!plan2.args.iter().any(|a| a == "--ignore-workspace"));
    }

    #[test]
    fn plan_install_disabled_by_config() {
        let d = tmp();
        write(&d, "package.json", "{}");
        write(&d, "pnpm-lock.yaml", "");
        assert!(plan_install_with(&d, &test_cfg(false, true)).is_none());
    }

    #[test]
    fn package_manager_as_str() {
        assert_eq!(PackageManager::Pnpm.as_str(), "pnpm");
        assert_eq!(PackageManager::YarnClassic.as_str(), "yarn");
        assert_eq!(PackageManager::Npm.as_str(), "npm");
        assert_eq!(PackageManager::Bun.as_str(), "bun");
    }

    #[test]
    fn output_tail_handles_multibyte_cutoff() {
        // Build a buffer longer than max that ends with a multi-byte char straddling
        // a naive byte cutoff.
        let mut bytes = vec![b'a'; 50];
        bytes.extend("你好世界".as_bytes());
        let s = output_tail(&bytes, 10);
        assert!(s.starts_with('…') || s.chars().all(|c| !c.is_control()));
        // Must not panic and must be valid UTF-8 string content.
        assert!(!s.is_empty());
    }

    #[test]
    fn sanitize_path_drops_relative_entries() {
        let s = sanitize_path_for_bootstrap(".:/usr/bin:foo/bar:/opt/bin");
        assert_eq!(s, "/usr/bin:/opt/bin");
    }

    #[test]
    fn frozen_lockfile_error_detection() {
        assert!(looks_like_frozen_lockfile_error(
            b"ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with \"frozen-lockfile\"",
            b""
        ));
        assert!(!looks_like_frozen_lockfile_error(b"network error", b""));
    }
}
